package com.ljw.spring_cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-10T00:41:36.526+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://service.spring_cxf.ljw.com/", name = "ICalculateService")
public interface ICalculateService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.spring_cxf.ljw.com/", className = "com.ljw.spring_cxf.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.spring_cxf.ljw.com/", className = "com.ljw.spring_cxf.service.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
